compat: Fix MSYS2 platform build
To build with MSYS2, we don't need to use these trivial macros on cfl_compat.h.

Otherwise, they cause the following errors:

```log
In file included from C:\Users\cosmo\Documents\GitHub\cfl\src\cfl_time.c:29:
C:/Users/cosmo/Documents/GitHub/cfl/include/cfl/cfl_compat.h:40:16: error: '__tzname' declared as function returning an array
   40 | #define tzname _tzname
      |                ^~~~~~~
C:/Users/cosmo/Documents/GitHub/cfl/include/cfl/cfl_compat.h:40:16: error: conflicting types for '__tzname'; have 'int(
'
C:/Ruby31-x64/msys64/ucrt64/include/time.h:123:26: note: previous declaration of '__tzname' with type 'char **(void)'
  123 |   _CRTIMP char **__cdecl __tzname(void);
      |                          ^~~~~~~~
C:/Users/cosmo/Documents/GitHub/cfl/include/cfl/cfl_compat.h:39:18: error: expected '{' before '(' token
   39 | #define timezone _timezone
      |                  ^~~~~~~~~
C:/Users/cosmo/Documents/GitHub/cfl/include/cfl/cfl_compat.h:39:18: error: expected '{' before '(' token
   39 | #define timezone _timezone
      |                  ^~~~~~~~~
mingw32-make[2]: *** [src\CMakeFiles\cfl-static.dir\build.make:121: src/CMakeFiles/cfl-static.dir/cfl_time.c.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:157: src/CMakeFiles/cfl-static.dir/all] Error 2
```

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>